/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2018-10-25 04:40:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Login Form</title>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n");
      out.write("\n");
      out.write("<title>Restaurant Management System</title>\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"rest.css\" />\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("  \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("  <h1 id=\"grill\">Grill And Chill Restaurant</h1>\n");
      out.write("\t<img src=\"img/logo.jpg\" id=\"img\"></img>\n");
      out.write("  \t <nav id=\"menu\">\n");
      out.write("  <label for=\"tm\" id=\"toggle-menu\">Restaurant <span class=\"drop-icon\"></span></label>\n");
      out.write("  <input type=\"checkbox\" id=\"tm\">\n");
      out.write("  <ul class=\"main-menu clearfix\">\n");
      out.write("    <li><a href=\"rest2.jsp\" style=\"text-decoration: none;\">Home</a></li>\n");
      out.write("    <li><a href=\"login.jsp\" style=\"text-decoration: none;\">Login \n");
      out.write("        <span class=\"drop-icon\">â¾</span>\n");
      out.write("        <label title=\"Toggle Drop-down\" class=\"drop-icon\" for=\"sm1\">â¾</label>\n");
      out.write("      </a>\n");
      out.write("      <input type=\"checkbox\" id=\"sm1\">\n");
      out.write("      <ul class=\"sub-menu\">\n");
      out.write("        <li><a href=\"logout.jsp\" style=\"text-decoration: none;\">Logout</a></li>\n");
      out.write("       \n");
      out.write("\n");
      out.write("      </ul>\n");
      out.write("    </li>\n");
      out.write("            <li><a href=\"menudb.jsp\" style=\"text-decoration: none;\">Menu</a></li>\n");
      out.write("            <li><a href=\"online.jsp\" style=\"text-decoration: none;\">Reservation</a></li>\n");
      out.write("    <li><a href=\"about.jsp\" style=\"text-decoration: none;\">About</a></li>\n");
      out.write("\n");
      out.write("  </ul>\n");
      out.write("</nav>\n");
      out.write("\t\n");
      out.write("\t<div class=\"slideshow\">\n");
      out.write("\t<hr>\n");
      out.write("\t<img src =\"img/grill.jpg\"  id=\"slideimage\">\n");
      out.write("\t</div>\n");
      out.write("<script type=\"text/javascript\" src=\"Bootstrap/js/bootstrap.js\"></script>\n");
      out.write("\n");
      out.write("<div id=\"rest\">\n");
      out.write("\t<form  action=\"log\" method=\"post\" onsubmit=\"return validation()\">\n");
      out.write("\t<h2>Login</h2>\n");
      out.write("\t<input type=\"text\" name=\"user\" placeholder=\"username\" >\n");
      out.write("\n");
      out.write("\t<input type=\"password\" name=\"pass\" placeholder=\"password\">\n");
      out.write("\t<input type=\"submit\" name=\"sub_btn\" value=\"login\">\n");
      out.write("\t\n");
      out.write("\t<a href=\"registration.jsp\" id=\"log\">don`t have an account?</a><br>\n");
      out.write("\t<a href=\"#\" id=\"log\">Forget Password?</a>\n");
      out.write("\n");
      out.write("</form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  <footer style=\"\n");
      out.write("  text-align: center;\n");
      out.write("  padding: 10px;\n");
      out.write("  color:black;\n");
      out.write("  background-color:grey;\n");
      out.write("margin-top: 650px;\n");
      out.write("  bottom: 0;\n");
      out.write("  width: 100%;\"\n");
      out.write(">\n");
      out.write("    <div>\n");
      out.write("      &copy; 2018 | <a href=\"#\">Privacy Policy</a> <br> Website   designed by MMA\n");
      out.write("    </div>\n");
      out.write("  </footer>\n");
      out.write("\n");
      out.write(" \n");
      out.write(" \n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
