/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2018-10-25 04:38:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class rest2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<title>Restaurant Management System</title>\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"rest.css\" />\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("  body {\n");
      out.write("    background-color: lightblue;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (min-width: 400px) {\n");
      out.write("    body {\n");
      out.write("        background-color: lightblue;\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (min-width: 800px) {\n");
      out.write("    body {\n");
      out.write("        background-color: lavender;\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (min-width: 400px) {\n");
      out.write("   #welcome{\n");
      out.write("    margin-right: 20px;\n");
      out.write("   } \n");
      out.write("  .special{\n");
      out.write("    margin-top: -20px;\n");
      out.write("   } \n");
      out.write("   \n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (min-width: 800px) {\n");
      out.write("  #welcome{\n");
      out.write("    margin-right: 20px;\n");
      out.write("   } \n");
      out.write("   .special{\n");
      out.write("    margin-top: -20px;\n");
      out.write("   }\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("  \n");
      out.write("\t </head>\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("\n");
      out.write("   <h1 id=\"grill\">Grill And Chill Restaurant</h1>\n");
      out.write("\t<img src=\"img/logo.jpg\" id=\"img\"></img>\n");
      out.write("    <nav id=\"menu\">\n");
      out.write("    <label for=\"tm\" id=\"toggle-menu\">Restaurant <span class=\"drop-icon\"></span></label>\n");
      out.write("  <input type=\"checkbox\" id=\"tm\">\n");
      out.write("  <ul class=\"main-menu clearfix\">\n");
      out.write("    <li><a href=\"rest2.jsp\" style=\"text-decoration: none;\">Home</a></li>\n");
      out.write("    <li><a href=\"login.jsp\" style=\"text-decoration: none;\">Login \n");
      out.write("        <span class=\"drop-icon\"></span>\n");
      out.write("        <label title=\"Toggle Drop-down\" class=\"drop-icon\" for=\"sm1\"></label>\n");
      out.write("      </a>\n");
      out.write("      <input type=\"checkbox\" id=\"sm1\">\n");
      out.write("      <ul class=\"sub-menu\">\n");
      out.write("        <li><a href=\"logout.jsp\" style=\"text-decoration: none;\">Logout</a></li>\n");
      out.write("       \n");
      out.write("\n");
      out.write("      </ul>\n");
      out.write("    </li>\n");
      out.write("            <li><a href=\"menudb.jsp\" style=\"text-decoration: none;\">Menu</a></li>\n");
      out.write("            <li><a href=\"online.jsp\" style=\"text-decoration: none;\">Reservation</a></li>\n");
      out.write("    <li><a href=\"about.jsp\" style=\"text-decoration: none;\">About</a></li>\n");
      out.write("\n");
      out.write("  </ul>\n");
      out.write("</nav>\n");
      out.write("\t<div class=\"slideshow\">\n");
      out.write("\t<hr>\n");
      out.write("\t<img src =\"img/grill.jpg\"  id=\"slideimage\">\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write(" <div id=\"welcome\">\n");
      out.write(" <header>\n");
      out.write(" <nav>\n");
      out.write(" \t<h4 id=\"head\">Welcome To Grill and Chill</h4>\n");
      out.write(" <div>\n");
      out.write("  \t<p id=\"paragraph\">We Specialize in delicious and resonably priced cuisine ,including our house specialities.Our extensive menu features chinese and indian dishes as well as filipine dish,all prepared using our secret family reciped whether you are in the mood to try something new or just want to enjoy some old favourites,we can assure you that our food and service will leave you satisfie.<span id=\"dots\">...</span><span id=\"more\">\n");
      out.write("  \t\tThis purposed application will manage all the needs from both ends from customer and as well as from management end.By using this application any organization can manage its all on going processes and also can generate reports that are very much important and fruitful in the growth of organization. </span> </p>\n");
      out.write("      </div>\n");
      out.write("  \t<button onclick=\"myFunction()\" id=\"myBtn\">Read more</button>\n");
      out.write("   </nav>\n");
      out.write("   </header>\n");
      out.write("   </div>\n");
      out.write("   \n");
      out.write("<div class=\"special\">\n");
      out.write("<h2 id=\"todays\">Todays special</h2>\n");
      out.write("<img src=\"img/25per.jpg\" id=\"kabab\">\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("  \t\n");
      out.write("<div class=\"container_12\">\n");
      out.write("    <div class=\"grid_12\">\n");
      out.write("      <h1 >New in Menu</h1>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"gallery\">\n");
      out.write("    <div class=\"grid_3\">\n");
      out.write("      <div class=\"box maxheight\">\n");
      out.write("     \n");
      out.write("        <img src=\"img/box_img4.jpg\" alt=\"\">\n");
      out.write("        <div class=\"title\">Vestibulum volu</div>\n");
      out.write("        Convallis orci vel mi oreet, at kotornare lorem consequat. Sellus era nisl auctor vel veliterolvenenatis nulla. \n");
      out.write("        <br>\n");
      out.write("        <a href=\"#\">More Info</a>\n");
      out.write("       \n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"grid_3\">\n");
      out.write("      <div class=\"box maxheight\">\n");
      out.write("      \n");
      out.write("        <img src=\"img/box_img2.jpg\" alt=\"\">\n");
      out.write("        <div class=\"title\">Aliquamh ante</div>\n");
      out.write("        Benteger convallis orci veli elaoreet, at ornare loremo konsequat. Phasellus era nisl auctor vel veliterut. \n");
      out.write("        <br>\n");
      out.write("        <a href=\"#\">More Info</a>\n");
      out.write("      \n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"grid_3\">\n");
      out.write("      <div class=\"box maxheight\">\n");
      out.write("     \n");
      out.write("        <img src=\"img/box_img3.jpg\" alt=\"\">\n");
      out.write("        <div class=\"title\">Ulum volutpat</div>\n");
      out.write("        Hrtolieger convallis omi tem aore, at ornare loren coate. Pasellus era nisl auctor vel veliterolsed pharetra. \n");
      out.write("        <br>\n");
      out.write("        <a href=\"#\">More Info</a>\n");
      out.write("       \n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("function myFunction() {\n");
      out.write("  var dots = document.getElementById(\"dots\");\n");
      out.write("  var moreText = document.getElementById(\"more\");\n");
      out.write("  var btnText = document.getElementById(\"myBtn\");\n");
      out.write("\n");
      out.write("  if (dots.style.display === \"none\") {\n");
      out.write("    dots.style.display = \"inline\";\n");
      out.write("    btnText.innerHTML = \"Read more\"; \n");
      out.write("    moreText.style.display = \"none\";\n");
      out.write("  } else {\n");
      out.write("    dots.style.display = \"none\";\n");
      out.write("    btnText.innerHTML = \"Read less\"; \n");
      out.write("    moreText.style.display = \"inline\";\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("    \n");
      out.write("<script src=\"rest.js\"></script>\n");
      out.write("\n");
      out.write("<footer>  \n");
      out.write("       <div class=\"copy\" style=\"margin-bottom: 0;margin-left: 10px\">\n");
      out.write("     &copy; 2018 | <a href=\"#\">Privacy Policy</a><br> Website   designed by MMA\n");
      out.write("      </div>\n");
      out.write("  \n");
      out.write(" \n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\t");
 
		if ((session.getAttribute("user") == null) || (session.getAttribute("user") == "")) 
    {	
      out.write("\n");
      out.write("\t    \n");
      out.write("\t\n");
      out.write("  ");
   }    
    
	else
    {
	
	  session.getAttribute("user");
	
      out.write("\n");
      out.write("\t <span style=\"font-size:1.30em; color:black; font-weight:bold;text-align:center;display:block;padding:20px;position: absolute;top: 257px;left: 1000px;\">Welcome ");
      out.print(session.getAttribute("user"));
      out.write("</span>\n");
      out.write("\t\n");
      out.write(" ");
 }
 
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
